Elastic Net

In [ ]:
import  pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
tips = sns.load_dataset("tips")

In [ ]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips = pd.get_dummies(tips)

In [ ]:
tips.head(10)

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,True,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,True,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,True,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,True,False,False,False,True,False,True
5,25.29,4.71,4,True,False,False,True,False,False,False,True,False,True
6,8.77,2.00,2,True,False,False,True,False,False,False,True,False,True
7,26.88,3.12,4,True,False,False,True,False,False,False,True,False,True
8,15.04,1.96,2,True,False,False,True,False,False,False,True,False,True
9,14.78,3.23,2,True,False,False,True,False,False,False,True,False,True

In [ ]:
X = tips.drop("tip", axis=1)

In [ ]:
y = tips["tip"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)

In [ ]:
X_test = scaler.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import ElasticNet

In [ ]:
elastic_net = ElasticNet()

In [ ]:
elastic_net.fit(X_train, y_train)

ElasticNet()

In [ ]:
y_pred = elastic_net.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
mean_absolute_error(y_test, y_pred)

0.8914346405765079

In [ ]:
mean_squared_error(y_test, y_pred)

1.024442390960209

In [ ]:
r2_score(y_test, y_pred)

0.1804272995261127

In [ ]:
param_grid = {
    "alpha" : [ 0.1, 0.3, 0.5, 0.7, 0.9, 1.0],
    "l1_ratio": [ 0.1, 0.3, 0.5, 0.7, 0.9, 1.0]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
elastic_cv = GridSearchCV(elastic_net, param_grid, cv=3, scoring="neg_mean_squared_error")

In [ ]:
elastic_cv.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 0.3, 0.5, 0.7, 0.9, 1.0],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]},
             scoring='neg_mean_squared_error')

In [ ]:
y_pred2 = elastic_cv.predict(X_test)

In [ ]:
mean_absolute_error(y_test, y_pred2)

0.7266777001047485

In [ ]:
mean_squared_error(y_test, y_pred2)

0.7374166023405732

In [ ]:
r2_score(y_test, y_pred2)

0.4100531943157194